AWSTemplateFormatVersion: '2010-09-09'
Description: > 
   Schedule or delay message publication on an AWS SNS topic using a
   simple Step Functions state machine with two tasks: Wait, SNS.

Resources:
    # Step Functions state machine that delays, then publishes to SNS topic.
    StepFunctionsStateMachine:
        Type: "AWS::StepFunctions::StateMachine"
        Properties:
            StateMachineName: DelayedSNS
            RoleArn: !GetAtt StepFunctionsServiceRole.Arn
            # Replace "SecondsPath" with "TimestampPath" for scheduling
            DefinitionString:
              Fn::Sub: |
                {
                  "StartAt": "Delay",
                  "Comment": "Publish to SNS with delay",
                  "States": {
                    "Delay": {
                      "Type": "Wait",
                      "TimestampPath": "$.delay_timestamp",
                      "Next": "Publish to SNS"
                    },
                    "Publish to SNS": {
                      "Type": "Task",
                      "Resource": "arn:aws:states:::sns:publish",
                      "Parameters": {
                        "TopicArn.$": "$.sns_topic",
                        "Message.$": "$.message"
                      },
                      "End": true
                    }
                  }
                }

    # Allow Step Functions state machine to publish to SNS topic
    StepFunctionsServiceRole:
        Type: "AWS::IAM::Role"
        Properties:
            Path: !Join ["", ["/", !Ref "AWS::StackName", "/"]]
            ManagedPolicyArns:
                - "arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess"
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    -
                        Sid: "AllowStepFunctionsServiceToAssumeRole"
                        Effect: "Allow"
                        Action: 
                            - "sts:AssumeRole"
                        Principal:
                            Service:
                                - !Sub "states.${AWS::Region}.amazonaws.com"
            Policies:
                -   PolicyName: "PublishToSNSTopic"
                    PolicyDocument:
                        Version: '2012-10-17'
                        Statement:
                            -   Effect: "Allow"
                                Action:
                                    - "sns:Publish"
                                Resource: 
                                    - "*"

Outputs:
    StepFunctionsStateMachine:
        Description: Step Functions State Machine ARN
        Value: !Ref StepFunctionsStateMachine
